# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

# Class that represents UI elements

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.seg1_116 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_116.setGeometry(QtCore.QRect(870, 160, 61, 41))
        self.seg1_116.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_116.setAutoFillBackground(True)
        self.seg1_116.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_116.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_116.setDigitCount(2)
        self.seg1_116.setObjectName("seg1_116")
        self.seg1_176 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_176.setGeometry(QtCore.QRect(620, 160, 61, 41))
        self.seg1_176.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_176.setAutoFillBackground(True)
        self.seg1_176.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_176.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_176.setDigitCount(2)
        self.seg1_176.setObjectName("seg1_176")
        self.seg1_109 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_109.setGeometry(QtCore.QRect(500, 160, 61, 41))
        self.seg1_109.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_109.setAutoFillBackground(True)
        self.seg1_109.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_109.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_109.setDigitCount(2)
        self.seg1_109.setObjectName("seg1_109")
        self.seg1_238 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_238.setGeometry(QtCore.QRect(440, 480, 61, 41))
        self.seg1_238.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_238.setAutoFillBackground(True)
        self.seg1_238.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_238.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_238.setDigitCount(2)
        self.seg1_238.setObjectName("seg1_238")
        self.seg1_174 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_174.setGeometry(QtCore.QRect(870, 40, 61, 41))
        self.seg1_174.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_174.setAutoFillBackground(True)
        self.seg1_174.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_174.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_174.setDigitCount(2)
        self.seg1_174.setObjectName("seg1_174")
        self.seg1_270 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_270.setGeometry(QtCore.QRect(810, 320, 61, 41))
        self.seg1_270.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_270.setAutoFillBackground(True)
        self.seg1_270.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_270.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_270.setDigitCount(2)
        self.seg1_270.setObjectName("seg1_270")
        self.seg1_236 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_236.setGeometry(QtCore.QRect(750, 400, 61, 41))
        self.seg1_236.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_236.setAutoFillBackground(True)
        self.seg1_236.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_236.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_236.setDigitCount(2)
        self.seg1_236.setObjectName("seg1_236")
        self.seg1_274 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_274.setGeometry(QtCore.QRect(500, 440, 61, 41))
        self.seg1_274.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_274.setAutoFillBackground(True)
        self.seg1_274.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_274.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_274.setDigitCount(2)
        self.seg1_274.setObjectName("seg1_274")
        self.seg1_209 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_209.setGeometry(QtCore.QRect(70, 360, 61, 41))
        self.seg1_209.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_209.setAutoFillBackground(True)
        self.seg1_209.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_209.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_209.setDigitCount(2)
        self.seg1_209.setObjectName("seg1_209")
        self.seg1_203 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_203.setGeometry(QtCore.QRect(930, 160, 61, 41))
        self.seg1_203.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_203.setAutoFillBackground(True)
        self.seg1_203.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_203.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_203.setDigitCount(2)
        self.seg1_203.setObjectName("seg1_203")
        self.seg1_235 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_235.setGeometry(QtCore.QRect(560, 480, 61, 41))
        self.seg1_235.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_235.setAutoFillBackground(True)
        self.seg1_235.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_235.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_235.setDigitCount(2)
        self.seg1_235.setObjectName("seg1_235")
        self.seg1_219 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_219.setGeometry(QtCore.QRect(930, 440, 61, 41))
        self.seg1_219.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_219.setAutoFillBackground(True)
        self.seg1_219.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_219.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_219.setDigitCount(2)
        self.seg1_219.setObjectName("seg1_219")
        self.seg1_158 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_158.setGeometry(QtCore.QRect(250, 120, 61, 41))
        self.seg1_158.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_158.setAutoFillBackground(True)
        self.seg1_158.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_158.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_158.setDigitCount(2)
        self.seg1_158.setObjectName("seg1_158")
        self.seg1_105 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_105.setGeometry(QtCore.QRect(10, 80, 61, 41))
        self.seg1_105.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_105.setAutoFillBackground(True)
        self.seg1_105.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_105.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_105.setDigitCount(2)
        self.seg1_105.setObjectName("seg1_105")
        self.seg1_126 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_126.setGeometry(QtCore.QRect(190, 40, 61, 41))
        self.seg1_126.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_126.setAutoFillBackground(True)
        self.seg1_126.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_126.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_126.setDigitCount(2)
        self.seg1_126.setObjectName("seg1_126")
        self.seg1_125 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_125.setGeometry(QtCore.QRect(500, 400, 61, 41))
        self.seg1_125.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_125.setAutoFillBackground(True)
        self.seg1_125.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_125.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_125.setDigitCount(2)
        self.seg1_125.setObjectName("seg1_125")
        self.seg1_213 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_213.setGeometry(QtCore.QRect(10, 440, 61, 41))
        self.seg1_213.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_213.setAutoFillBackground(True)
        self.seg1_213.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_213.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_213.setDigitCount(2)
        self.seg1_213.setObjectName("seg1_213")
        self.seg1_251 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_251.setGeometry(QtCore.QRect(810, 480, 61, 41))
        self.seg1_251.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_251.setAutoFillBackground(True)
        self.seg1_251.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_251.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_251.setDigitCount(2)
        self.seg1_251.setObjectName("seg1_251")
        self.seg1_196 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_196.setGeometry(QtCore.QRect(810, 120, 61, 41))
        self.seg1_196.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_196.setAutoFillBackground(True)
        self.seg1_196.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_196.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_196.setDigitCount(2)
        self.seg1_196.setObjectName("seg1_196")
        self.seg1_284 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_284.setGeometry(QtCore.QRect(70, 480, 61, 41))
        self.seg1_284.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_284.setAutoFillBackground(True)
        self.seg1_284.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_284.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_284.setDigitCount(2)
        self.seg1_284.setObjectName("seg1_284")
        self.seg1_156 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_156.setGeometry(QtCore.QRect(310, 200, 61, 41))
        self.seg1_156.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_156.setAutoFillBackground(True)
        self.seg1_156.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_156.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_156.setDigitCount(2)
        self.seg1_156.setObjectName("seg1_156")
        self.seg1_240 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_240.setGeometry(QtCore.QRect(440, 400, 61, 41))
        self.seg1_240.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_240.setAutoFillBackground(True)
        self.seg1_240.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_240.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_240.setDigitCount(2)
        self.seg1_240.setObjectName("seg1_240")
        self.seg1_111 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_111.setGeometry(QtCore.QRect(750, 240, 61, 41))
        self.seg1_111.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_111.setAutoFillBackground(True)
        self.seg1_111.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_111.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_111.setDigitCount(2)
        self.seg1_111.setObjectName("seg1_111")
        self.seg1_168 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_168.setGeometry(QtCore.QRect(190, 80, 61, 41))
        self.seg1_168.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_168.setAutoFillBackground(True)
        self.seg1_168.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_168.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_168.setDigitCount(2)
        self.seg1_168.setObjectName("seg1_168")
        self.seg1_210 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_210.setGeometry(QtCore.QRect(870, 320, 61, 41))
        self.seg1_210.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_210.setAutoFillBackground(True)
        self.seg1_210.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_210.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_210.setDigitCount(2)
        self.seg1_210.setObjectName("seg1_210")
        self.seg1_214 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_214.setGeometry(QtCore.QRect(380, 400, 61, 41))
        self.seg1_214.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_214.setAutoFillBackground(True)
        self.seg1_214.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_214.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_214.setDigitCount(2)
        self.seg1_214.setObjectName("seg1_214")
        self.seg1_263 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_263.setGeometry(QtCore.QRect(1050, 440, 61, 41))
        self.seg1_263.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_263.setAutoFillBackground(True)
        self.seg1_263.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_263.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_263.setDigitCount(2)
        self.seg1_263.setObjectName("seg1_263")
        self.seg1_264 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_264.setGeometry(QtCore.QRect(680, 400, 61, 41))
        self.seg1_264.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_264.setAutoFillBackground(True)
        self.seg1_264.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_264.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_264.setDigitCount(2)
        self.seg1_264.setObjectName("seg1_264")
        self.seg1_169 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_169.setGeometry(QtCore.QRect(680, 40, 61, 41))
        self.seg1_169.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_169.setAutoFillBackground(True)
        self.seg1_169.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_169.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_169.setDigitCount(2)
        self.seg1_169.setObjectName("seg1_169")
        self.seg1_261 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_261.setGeometry(QtCore.QRect(10, 320, 61, 41))
        self.seg1_261.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_261.setAutoFillBackground(True)
        self.seg1_261.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_261.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_261.setDigitCount(2)
        self.seg1_261.setObjectName("seg1_261")
        self.seg1_231 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_231.setGeometry(QtCore.QRect(380, 480, 61, 41))
        self.seg1_231.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_231.setAutoFillBackground(True)
        self.seg1_231.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_231.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_231.setDigitCount(2)
        self.seg1_231.setObjectName("seg1_231")
        self.seg1_188 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_188.setGeometry(QtCore.QRect(440, 120, 61, 41))
        self.seg1_188.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_188.setAutoFillBackground(True)
        self.seg1_188.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_188.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_188.setDigitCount(2)
        self.seg1_188.setObjectName("seg1_188")
        self.seg1_108 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_108.setGeometry(QtCore.QRect(380, 80, 61, 41))
        self.seg1_108.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_108.setAutoFillBackground(True)
        self.seg1_108.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_108.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_108.setDigitCount(2)
        self.seg1_108.setObjectName("seg1_108")
        self.seg1_118 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_118.setGeometry(QtCore.QRect(440, 320, 61, 41))
        self.seg1_118.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_118.setAutoFillBackground(True)
        self.seg1_118.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_118.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_118.setDigitCount(2)
        self.seg1_118.setObjectName("seg1_118")
        self.seg1_144 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_144.setGeometry(QtCore.QRect(1050, 80, 61, 41))
        self.seg1_144.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_144.setAutoFillBackground(True)
        self.seg1_144.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_144.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_144.setDigitCount(2)
        self.seg1_144.setObjectName("seg1_144")
        self.seg1_136 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_136.setGeometry(QtCore.QRect(70, 200, 61, 41))
        self.seg1_136.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_136.setAutoFillBackground(True)
        self.seg1_136.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_136.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_136.setDigitCount(2)
        self.seg1_136.setObjectName("seg1_136")
        self.seg1_138 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_138.setGeometry(QtCore.QRect(10, 120, 61, 41))
        self.seg1_138.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_138.setAutoFillBackground(True)
        self.seg1_138.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_138.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_138.setDigitCount(2)
        self.seg1_138.setObjectName("seg1_138")
        self.seg1_253 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_253.setGeometry(QtCore.QRect(1050, 360, 61, 41))
        self.seg1_253.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_253.setAutoFillBackground(True)
        self.seg1_253.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_253.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_253.setDigitCount(2)
        self.seg1_253.setObjectName("seg1_253")
        self.seg1_227 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_227.setGeometry(QtCore.QRect(1050, 480, 61, 41))
        self.seg1_227.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_227.setAutoFillBackground(True)
        self.seg1_227.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_227.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_227.setDigitCount(2)
        self.seg1_227.setObjectName("seg1_227")
        self.seg1_171 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_171.setGeometry(QtCore.QRect(680, 160, 61, 41))
        self.seg1_171.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_171.setAutoFillBackground(True)
        self.seg1_171.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_171.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_171.setDigitCount(2)
        self.seg1_171.setObjectName("seg1_171")
        self.seg1_280 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_280.setGeometry(QtCore.QRect(750, 480, 61, 41))
        self.seg1_280.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_280.setAutoFillBackground(True)
        self.seg1_280.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_280.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_280.setDigitCount(2)
        self.seg1_280.setObjectName("seg1_280")
        self.seg1_127 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_127.setGeometry(QtCore.QRect(70, 160, 61, 41))
        self.seg1_127.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_127.setAutoFillBackground(True)
        self.seg1_127.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_127.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_127.setDigitCount(2)
        self.seg1_127.setObjectName("seg1_127")
        self.seg1_128 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_128.setGeometry(QtCore.QRect(560, 40, 61, 41))
        self.seg1_128.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_128.setAutoFillBackground(True)
        self.seg1_128.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_128.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_128.setDigitCount(2)
        self.seg1_128.setObjectName("seg1_128")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 290, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(True)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.seg1_155 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_155.setGeometry(QtCore.QRect(560, 160, 61, 41))
        self.seg1_155.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_155.setAutoFillBackground(True)
        self.seg1_155.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_155.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_155.setDigitCount(2)
        self.seg1_155.setObjectName("seg1_155")
        self.seg1_121 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_121.setGeometry(QtCore.QRect(130, 480, 61, 41))
        self.seg1_121.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_121.setAutoFillBackground(True)
        self.seg1_121.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_121.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_121.setDigitCount(2)
        self.seg1_121.setObjectName("seg1_121")
        self.seg1_205 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_205.setGeometry(QtCore.QRect(10, 400, 61, 41))
        self.seg1_205.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_205.setAutoFillBackground(True)
        self.seg1_205.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_205.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_205.setDigitCount(2)
        self.seg1_205.setObjectName("seg1_205")
        self.seg1_131 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_131.setGeometry(QtCore.QRect(930, 40, 61, 41))
        self.seg1_131.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_131.setAutoFillBackground(True)
        self.seg1_131.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_131.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_131.setDigitCount(2)
        self.seg1_131.setObjectName("seg1_131")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(380, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.seg1_115 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_115.setGeometry(QtCore.QRect(810, 40, 61, 41))
        self.seg1_115.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_115.setAutoFillBackground(True)
        self.seg1_115.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_115.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_115.setDigitCount(2)
        self.seg1_115.setObjectName("seg1_115")
        self.seg1_170 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_170.setGeometry(QtCore.QRect(560, 80, 61, 41))
        self.seg1_170.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_170.setAutoFillBackground(True)
        self.seg1_170.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_170.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_170.setDigitCount(2)
        self.seg1_170.setObjectName("seg1_170")
        self.seg1_141 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_141.setGeometry(QtCore.QRect(680, 80, 61, 41))
        self.seg1_141.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_141.setAutoFillBackground(True)
        self.seg1_141.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_141.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_141.setDigitCount(2)
        self.seg1_141.setObjectName("seg1_141")
        self.seg1_165 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_165.setGeometry(QtCore.QRect(380, 200, 61, 41))
        self.seg1_165.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_165.setAutoFillBackground(True)
        self.seg1_165.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_165.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_165.setDigitCount(2)
        self.seg1_165.setObjectName("seg1_165")
        self.seg1_124 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_124.setGeometry(QtCore.QRect(870, 480, 61, 41))
        self.seg1_124.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_124.setAutoFillBackground(True)
        self.seg1_124.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_124.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_124.setDigitCount(2)
        self.seg1_124.setObjectName("seg1_124")
        self.seg1_154 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_154.setGeometry(QtCore.QRect(190, 160, 61, 41))
        self.seg1_154.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_154.setAutoFillBackground(True)
        self.seg1_154.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_154.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_154.setDigitCount(2)
        self.seg1_154.setObjectName("seg1_154")
        self.seg1_215 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_215.setGeometry(QtCore.QRect(1050, 400, 61, 41))
        self.seg1_215.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_215.setAutoFillBackground(True)
        self.seg1_215.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_215.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_215.setDigitCount(2)
        self.seg1_215.setObjectName("seg1_215")
        self.seg1_179 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_179.setGeometry(QtCore.QRect(130, 80, 61, 41))
        self.seg1_179.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_179.setAutoFillBackground(True)
        self.seg1_179.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_179.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_179.setDigitCount(2)
        self.seg1_179.setObjectName("seg1_179")
        self.seg1_148 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_148.setGeometry(QtCore.QRect(380, 160, 61, 41))
        self.seg1_148.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_148.setAutoFillBackground(True)
        self.seg1_148.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_148.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_148.setDigitCount(2)
        self.seg1_148.setObjectName("seg1_148")
        self.seg1_229 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_229.setGeometry(QtCore.QRect(680, 360, 61, 41))
        self.seg1_229.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_229.setAutoFillBackground(True)
        self.seg1_229.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_229.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_229.setDigitCount(2)
        self.seg1_229.setObjectName("seg1_229")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.seg1_164 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_164.setGeometry(QtCore.QRect(10, 200, 61, 41))
        self.seg1_164.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_164.setAutoFillBackground(True)
        self.seg1_164.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_164.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_164.setDigitCount(2)
        self.seg1_164.setObjectName("seg1_164")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.seg1_267 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_267.setGeometry(QtCore.QRect(70, 400, 61, 41))
        self.seg1_267.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_267.setAutoFillBackground(True)
        self.seg1_267.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_267.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_267.setDigitCount(2)
        self.seg1_267.setObjectName("seg1_267")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(10, 590, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.seg1_288 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_288.setGeometry(QtCore.QRect(250, 480, 61, 41))
        self.seg1_288.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_288.setAutoFillBackground(True)
        self.seg1_288.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_288.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_288.setDigitCount(2)
        self.seg1_288.setObjectName("seg1_288")
        self.seg1_166 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_166.setGeometry(QtCore.QRect(310, 40, 61, 41))
        self.seg1_166.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_166.setAutoFillBackground(True)
        self.seg1_166.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_166.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_166.setDigitCount(2)
        self.seg1_166.setObjectName("seg1_166")
        self.seg1_255 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_255.setGeometry(QtCore.QRect(310, 320, 61, 41))
        self.seg1_255.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_255.setAutoFillBackground(True)
        self.seg1_255.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_255.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_255.setDigitCount(2)
        self.seg1_255.setObjectName("seg1_255")
        self.seg1_286 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_286.setGeometry(QtCore.QRect(310, 360, 61, 41))
        self.seg1_286.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_286.setAutoFillBackground(True)
        self.seg1_286.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_286.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_286.setDigitCount(2)
        self.seg1_286.setObjectName("seg1_286")
        self.seg1_257 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_257.setGeometry(QtCore.QRect(750, 320, 61, 41))
        self.seg1_257.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_257.setAutoFillBackground(True)
        self.seg1_257.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_257.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_257.setDigitCount(2)
        self.seg1_257.setObjectName("seg1_257")
        self.seg1_112 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_112.setGeometry(QtCore.QRect(750, 80, 61, 41))
        self.seg1_112.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_112.setAutoFillBackground(True)
        self.seg1_112.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_112.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_112.setDigitCount(2)
        self.seg1_112.setObjectName("seg1_112")
        self.averageTemp2_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp2_LCD.setGeometry(QtCore.QRect(260, 610, 71, 51))
        self.averageTemp2_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp2_LCD.setAutoFillBackground(True)
        self.averageTemp2_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp2_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp2_LCD.setDigitCount(2)
        self.averageTemp2_LCD.setObjectName("averageTemp2_LCD")
        self.seg1_142 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_142.setGeometry(QtCore.QRect(810, 200, 61, 41))
        self.seg1_142.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_142.setAutoFillBackground(True)
        self.seg1_142.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_142.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_142.setDigitCount(2)
        self.seg1_142.setObjectName("seg1_142")
        self.seg1_279 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_279.setGeometry(QtCore.QRect(810, 400, 61, 41))
        self.seg1_279.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_279.setAutoFillBackground(True)
        self.seg1_279.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_279.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_279.setDigitCount(2)
        self.seg1_279.setObjectName("seg1_279")
        self.seg1_180 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_180.setGeometry(QtCore.QRect(70, 80, 61, 41))
        self.seg1_180.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_180.setAutoFillBackground(True)
        self.seg1_180.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_180.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_180.setDigitCount(2)
        self.seg1_180.setObjectName("seg1_180")
        self.seg1_151 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_151.setGeometry(QtCore.QRect(190, 200, 61, 41))
        self.seg1_151.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_151.setAutoFillBackground(True)
        self.seg1_151.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_151.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_151.setDigitCount(2)
        self.seg1_151.setObjectName("seg1_151")
        self.seg1_244 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_244.setGeometry(QtCore.QRect(190, 440, 61, 41))
        self.seg1_244.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_244.setAutoFillBackground(True)
        self.seg1_244.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_244.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_244.setDigitCount(2)
        self.seg1_244.setObjectName("seg1_244")
        self.seg1_182 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_182.setGeometry(QtCore.QRect(440, 80, 61, 41))
        self.seg1_182.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_182.setAutoFillBackground(True)
        self.seg1_182.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_182.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_182.setDigitCount(2)
        self.seg1_182.setObjectName("seg1_182")
        self.seg1_216 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_216.setGeometry(QtCore.QRect(310, 400, 61, 41))
        self.seg1_216.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_216.setAutoFillBackground(True)
        self.seg1_216.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_216.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_216.setDigitCount(2)
        self.seg1_216.setObjectName("seg1_216")
        self.seg1_143 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_143.setGeometry(QtCore.QRect(750, 120, 61, 41))
        self.seg1_143.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_143.setAutoFillBackground(True)
        self.seg1_143.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_143.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_143.setDigitCount(2)
        self.seg1_143.setObjectName("seg1_143")
        self.seg1_276 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_276.setGeometry(QtCore.QRect(380, 520, 61, 41))
        self.seg1_276.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_276.setAutoFillBackground(True)
        self.seg1_276.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_276.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_276.setDigitCount(2)
        self.seg1_276.setObjectName("seg1_276")
        self.seg1_204 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_204.setGeometry(QtCore.QRect(750, 40, 61, 41))
        self.seg1_204.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_204.setAutoFillBackground(True)
        self.seg1_204.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_204.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_204.setDigitCount(2)
        self.seg1_204.setObjectName("seg1_204")
        self.seg1_135 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_135.setGeometry(QtCore.QRect(930, 320, 61, 41))
        self.seg1_135.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_135.setAutoFillBackground(True)
        self.seg1_135.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_135.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_135.setDigitCount(2)
        self.seg1_135.setObjectName("seg1_135")
        self.seg1_202 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_202.setGeometry(QtCore.QRect(990, 160, 61, 41))
        self.seg1_202.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_202.setAutoFillBackground(True)
        self.seg1_202.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_202.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_202.setDigitCount(2)
        self.seg1_202.setObjectName("seg1_202")
        self.seg1_206 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_206.setGeometry(QtCore.QRect(620, 400, 61, 41))
        self.seg1_206.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_206.setAutoFillBackground(True)
        self.seg1_206.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_206.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_206.setDigitCount(2)
        self.seg1_206.setObjectName("seg1_206")
        self.seg1_117 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_117.setGeometry(QtCore.QRect(10, 520, 61, 41))
        self.seg1_117.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_117.setAutoFillBackground(True)
        self.seg1_117.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_117.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_117.setDigitCount(2)
        self.seg1_117.setObjectName("seg1_117")
        self.seg1_186 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_186.setGeometry(QtCore.QRect(620, 200, 61, 41))
        self.seg1_186.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_186.setAutoFillBackground(True)
        self.seg1_186.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_186.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_186.setDigitCount(2)
        self.seg1_186.setObjectName("seg1_186")
        self.seg1_230 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_230.setGeometry(QtCore.QRect(440, 360, 61, 41))
        self.seg1_230.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_230.setAutoFillBackground(True)
        self.seg1_230.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_230.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_230.setDigitCount(2)
        self.seg1_230.setObjectName("seg1_230")
        self.seg1_199 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_199.setGeometry(QtCore.QRect(750, 200, 61, 41))
        self.seg1_199.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_199.setAutoFillBackground(True)
        self.seg1_199.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_199.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_199.setDigitCount(2)
        self.seg1_199.setObjectName("seg1_199")
        self.seg1_266 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_266.setGeometry(QtCore.QRect(310, 440, 61, 41))
        self.seg1_266.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_266.setAutoFillBackground(True)
        self.seg1_266.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_266.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_266.setDigitCount(2)
        self.seg1_266.setObjectName("seg1_266")
        self.seg1_265 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_265.setGeometry(QtCore.QRect(620, 440, 61, 41))
        self.seg1_265.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_265.setAutoFillBackground(True)
        self.seg1_265.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_265.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_265.setDigitCount(2)
        self.seg1_265.setObjectName("seg1_265")
        self.seg1_101 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_101.setGeometry(QtCore.QRect(500, 200, 61, 41))
        self.seg1_101.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_101.setAutoFillBackground(True)
        self.seg1_101.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_101.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_101.setDigitCount(2)
        self.seg1_101.setObjectName("seg1_101")
        self.seg1_254 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_254.setGeometry(QtCore.QRect(190, 480, 61, 41))
        self.seg1_254.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_254.setAutoFillBackground(True)
        self.seg1_254.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_254.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_254.setDigitCount(2)
        self.seg1_254.setObjectName("seg1_254")
        self.seg1_248 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_248.setGeometry(QtCore.QRect(990, 480, 61, 41))
        self.seg1_248.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_248.setAutoFillBackground(True)
        self.seg1_248.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_248.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_248.setDigitCount(2)
        self.seg1_248.setObjectName("seg1_248")
        self.seg1_114 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_114.setGeometry(QtCore.QRect(440, 40, 61, 41))
        self.seg1_114.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_114.setAutoFillBackground(True)
        self.seg1_114.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_114.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_114.setDigitCount(2)
        self.seg1_114.setObjectName("seg1_114")
        self.seg1_226 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_226.setGeometry(QtCore.QRect(70, 440, 61, 41))
        self.seg1_226.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_226.setAutoFillBackground(True)
        self.seg1_226.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_226.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_226.setDigitCount(2)
        self.seg1_226.setObjectName("seg1_226")
        self.seg1_132 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_132.setGeometry(QtCore.QRect(250, 40, 61, 41))
        self.seg1_132.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_132.setAutoFillBackground(True)
        self.seg1_132.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_132.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_132.setDigitCount(2)
        self.seg1_132.setObjectName("seg1_132")
        self.seg1_150 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_150.setGeometry(QtCore.QRect(130, 40, 61, 41))
        self.seg1_150.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_150.setAutoFillBackground(True)
        self.seg1_150.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_150.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_150.setDigitCount(2)
        self.seg1_150.setObjectName("seg1_150")
        self.seg1_282 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_282.setGeometry(QtCore.QRect(560, 320, 61, 41))
        self.seg1_282.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_282.setAutoFillBackground(True)
        self.seg1_282.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_282.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_282.setDigitCount(2)
        self.seg1_282.setObjectName("seg1_282")
        self.seg1_217 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_217.setGeometry(QtCore.QRect(990, 400, 61, 41))
        self.seg1_217.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_217.setAutoFillBackground(True)
        self.seg1_217.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_217.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_217.setDigitCount(2)
        self.seg1_217.setObjectName("seg1_217")
        self.seg1_157 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_157.setGeometry(QtCore.QRect(680, 200, 61, 41))
        self.seg1_157.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_157.setAutoFillBackground(True)
        self.seg1_157.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_157.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_157.setDigitCount(2)
        self.seg1_157.setObjectName("seg1_157")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(380, 290, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(True)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.seg1_271 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_271.setGeometry(QtCore.QRect(440, 440, 61, 41))
        self.seg1_271.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_271.setAutoFillBackground(True)
        self.seg1_271.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_271.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_271.setDigitCount(2)
        self.seg1_271.setObjectName("seg1_271")
        self.seg1_181 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_181.setGeometry(QtCore.QRect(620, 80, 61, 41))
        self.seg1_181.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_181.setAutoFillBackground(True)
        self.seg1_181.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_181.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_181.setDigitCount(2)
        self.seg1_181.setObjectName("seg1_181")
        self.seg1_211 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_211.setGeometry(QtCore.QRect(310, 480, 61, 41))
        self.seg1_211.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_211.setAutoFillBackground(True)
        self.seg1_211.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_211.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_211.setDigitCount(2)
        self.seg1_211.setObjectName("seg1_211")
        self.seg1_110 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_110.setGeometry(QtCore.QRect(380, 240, 61, 41))
        self.seg1_110.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_110.setAutoFillBackground(True)
        self.seg1_110.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_110.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_110.setDigitCount(2)
        self.seg1_110.setObjectName("seg1_110")
        self.seg1_194 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_194.setGeometry(QtCore.QRect(870, 80, 61, 41))
        self.seg1_194.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_194.setAutoFillBackground(True)
        self.seg1_194.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_194.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_194.setDigitCount(2)
        self.seg1_194.setObjectName("seg1_194")
        self.seg1_163 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_163.setGeometry(QtCore.QRect(620, 120, 61, 41))
        self.seg1_163.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_163.setAutoFillBackground(True)
        self.seg1_163.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_163.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_163.setDigitCount(2)
        self.seg1_163.setObjectName("seg1_163")
        self.seg1_228 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_228.setGeometry(QtCore.QRect(130, 360, 61, 41))
        self.seg1_228.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_228.setAutoFillBackground(True)
        self.seg1_228.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_228.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_228.setDigitCount(2)
        self.seg1_228.setObjectName("seg1_228")
        self.seg1_259 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_259.setGeometry(QtCore.QRect(870, 440, 61, 41))
        self.seg1_259.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_259.setAutoFillBackground(True)
        self.seg1_259.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_259.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_259.setDigitCount(2)
        self.seg1_259.setObjectName("seg1_259")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(True)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.seg1_123 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_123.setGeometry(QtCore.QRect(750, 520, 61, 41))
        self.seg1_123.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_123.setAutoFillBackground(True)
        self.seg1_123.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_123.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_123.setDigitCount(2)
        self.seg1_123.setObjectName("seg1_123")
        self.seg1_130 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_130.setGeometry(QtCore.QRect(810, 160, 61, 41))
        self.seg1_130.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_130.setAutoFillBackground(True)
        self.seg1_130.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_130.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_130.setDigitCount(2)
        self.seg1_130.setObjectName("seg1_130")
        self.seg1_232 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_232.setGeometry(QtCore.QRect(560, 400, 61, 41))
        self.seg1_232.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_232.setAutoFillBackground(True)
        self.seg1_232.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_232.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_232.setDigitCount(2)
        self.seg1_232.setObjectName("seg1_232")
        self.averageTemp4_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp4_LCD.setGeometry(QtCore.QRect(420, 610, 71, 51))
        self.averageTemp4_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp4_LCD.setAutoFillBackground(True)
        self.averageTemp4_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp4_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp4_LCD.setDigitCount(2)
        self.averageTemp4_LCD.setObjectName("averageTemp4_LCD")
        self.seg1_221 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_221.setGeometry(QtCore.QRect(70, 520, 61, 41))
        self.seg1_221.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_221.setAutoFillBackground(True)
        self.seg1_221.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_221.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_221.setDigitCount(2)
        self.seg1_221.setObjectName("seg1_221")
        self.seg1_260 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_260.setGeometry(QtCore.QRect(250, 440, 61, 41))
        self.seg1_260.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_260.setAutoFillBackground(True)
        self.seg1_260.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_260.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_260.setDigitCount(2)
        self.seg1_260.setObjectName("seg1_260")
        self.seg1_106 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_106.setGeometry(QtCore.QRect(10, 240, 61, 41))
        self.seg1_106.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_106.setAutoFillBackground(True)
        self.seg1_106.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_106.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_106.setDigitCount(2)
        self.seg1_106.setObjectName("seg1_106")
        self.seg1_287 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_287.setGeometry(QtCore.QRect(620, 320, 61, 41))
        self.seg1_287.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_287.setAutoFillBackground(True)
        self.seg1_287.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_287.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_287.setDigitCount(2)
        self.seg1_287.setObjectName("seg1_287")
        self.seg1_224 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_224.setGeometry(QtCore.QRect(500, 360, 61, 41))
        self.seg1_224.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_224.setAutoFillBackground(True)
        self.seg1_224.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_224.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_224.setDigitCount(2)
        self.seg1_224.setObjectName("seg1_224")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(750, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.seg1_175 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_175.setGeometry(QtCore.QRect(250, 160, 61, 41))
        self.seg1_175.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_175.setAutoFillBackground(True)
        self.seg1_175.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_175.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_175.setDigitCount(2)
        self.seg1_175.setObjectName("seg1_175")
        self.seg1_283 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_283.setGeometry(QtCore.QRect(190, 320, 61, 41))
        self.seg1_283.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_283.setAutoFillBackground(True)
        self.seg1_283.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_283.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_283.setDigitCount(2)
        self.seg1_283.setObjectName("seg1_283")
        self.seg1_104 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_104.setGeometry(QtCore.QRect(130, 400, 61, 41))
        self.seg1_104.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_104.setAutoFillBackground(True)
        self.seg1_104.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_104.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_104.setDigitCount(2)
        self.seg1_104.setObjectName("seg1_104")
        self.seg1_281 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_281.setGeometry(QtCore.QRect(440, 520, 61, 41))
        self.seg1_281.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_281.setAutoFillBackground(True)
        self.seg1_281.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_281.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_281.setDigitCount(2)
        self.seg1_281.setObjectName("seg1_281")
        self.seg1_129 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_129.setGeometry(QtCore.QRect(440, 160, 61, 41))
        self.seg1_129.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_129.setAutoFillBackground(True)
        self.seg1_129.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_129.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_129.setDigitCount(2)
        self.seg1_129.setObjectName("seg1_129")
        self.seg1_268 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_268.setGeometry(QtCore.QRect(680, 440, 61, 41))
        self.seg1_268.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_268.setAutoFillBackground(True)
        self.seg1_268.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_268.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_268.setDigitCount(2)
        self.seg1_268.setObjectName("seg1_268")
        self.seg1_193 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_193.setGeometry(QtCore.QRect(1050, 120, 61, 41))
        self.seg1_193.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_193.setAutoFillBackground(True)
        self.seg1_193.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_193.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_193.setDigitCount(2)
        self.seg1_193.setObjectName("seg1_193")
        self.seg1_273 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_273.setGeometry(QtCore.QRect(250, 360, 61, 41))
        self.seg1_273.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_273.setAutoFillBackground(True)
        self.seg1_273.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_273.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_273.setDigitCount(2)
        self.seg1_273.setObjectName("seg1_273")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.seg1_167 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_167.setGeometry(QtCore.QRect(310, 160, 61, 41))
        self.seg1_167.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_167.setAutoFillBackground(True)
        self.seg1_167.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_167.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_167.setDigitCount(2)
        self.seg1_167.setObjectName("seg1_167")
        self.seg1_242 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_242.setGeometry(QtCore.QRect(810, 360, 61, 41))
        self.seg1_242.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_242.setAutoFillBackground(True)
        self.seg1_242.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_242.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_242.setDigitCount(2)
        self.seg1_242.setObjectName("seg1_242")
        self.seg1_212 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_212.setGeometry(QtCore.QRect(190, 400, 61, 41))
        self.seg1_212.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_212.setAutoFillBackground(True)
        self.seg1_212.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_212.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_212.setDigitCount(2)
        self.seg1_212.setObjectName("seg1_212")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.seg1_147 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_147.setGeometry(QtCore.QRect(560, 120, 61, 41))
        self.seg1_147.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_147.setAutoFillBackground(True)
        self.seg1_147.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_147.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_147.setDigitCount(2)
        self.seg1_147.setObjectName("seg1_147")
        self.seg1_149 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_149.setGeometry(QtCore.QRect(750, 160, 61, 41))
        self.seg1_149.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_149.setAutoFillBackground(True)
        self.seg1_149.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_149.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_149.setDigitCount(2)
        self.seg1_149.setObjectName("seg1_149")
        self.seg1_183 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_183.setGeometry(QtCore.QRect(310, 120, 61, 41))
        self.seg1_183.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_183.setAutoFillBackground(True)
        self.seg1_183.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_183.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_183.setDigitCount(2)
        self.seg1_183.setObjectName("seg1_183")
        self.seg1_113 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_113.setGeometry(QtCore.QRect(70, 40, 61, 41))
        self.seg1_113.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_113.setAutoFillBackground(True)
        self.seg1_113.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_113.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_113.setDigitCount(2)
        self.seg1_113.setObjectName("seg1_113")
        self.seg1_187 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_187.setGeometry(QtCore.QRect(70, 120, 61, 41))
        self.seg1_187.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_187.setAutoFillBackground(True)
        self.seg1_187.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_187.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_187.setDigitCount(2)
        self.seg1_187.setObjectName("seg1_187")
        self.seg1_233 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_233.setGeometry(QtCore.QRect(10, 480, 61, 41))
        self.seg1_233.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_233.setAutoFillBackground(True)
        self.seg1_233.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_233.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_233.setDigitCount(2)
        self.seg1_233.setObjectName("seg1_233")
        self.seg1_256 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_256.setGeometry(QtCore.QRect(680, 480, 61, 41))
        self.seg1_256.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_256.setAutoFillBackground(True)
        self.seg1_256.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_256.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_256.setDigitCount(2)
        self.seg1_256.setObjectName("seg1_256")
        self.seg1_153 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_153.setGeometry(QtCore.QRect(560, 200, 61, 41))
        self.seg1_153.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_153.setAutoFillBackground(True)
        self.seg1_153.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_153.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_153.setDigitCount(2)
        self.seg1_153.setObjectName("seg1_153")
        self.seg1_103 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_103.setGeometry(QtCore.QRect(870, 200, 61, 41))
        self.seg1_103.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_103.setAutoFillBackground(True)
        self.seg1_103.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_103.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_103.setDigitCount(2)
        self.seg1_103.setObjectName("seg1_103")
        self.seg1_223 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_223.setGeometry(QtCore.QRect(560, 440, 61, 41))
        self.seg1_223.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_223.setAutoFillBackground(True)
        self.seg1_223.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_223.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_223.setDigitCount(2)
        self.seg1_223.setObjectName("seg1_223")
        self.seg1_250 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_250.setGeometry(QtCore.QRect(500, 320, 61, 41))
        self.seg1_250.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_250.setAutoFillBackground(True)
        self.seg1_250.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_250.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_250.setDigitCount(2)
        self.seg1_250.setObjectName("seg1_250")
        self.seg1_222 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_222.setGeometry(QtCore.QRect(250, 400, 61, 41))
        self.seg1_222.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_222.setAutoFillBackground(True)
        self.seg1_222.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_222.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_222.setDigitCount(2)
        self.seg1_222.setObjectName("seg1_222")
        self.seg1_107 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_107.setGeometry(QtCore.QRect(130, 160, 61, 41))
        self.seg1_107.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_107.setAutoFillBackground(True)
        self.seg1_107.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_107.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_107.setDigitCount(2)
        self.seg1_107.setObjectName("seg1_107")
        self.seg1_289 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_289.setGeometry(QtCore.QRect(500, 480, 61, 41))
        self.seg1_289.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_289.setAutoFillBackground(True)
        self.seg1_289.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_289.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_289.setDigitCount(2)
        self.seg1_289.setObjectName("seg1_289")
        self.seg1_172 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_172.setGeometry(QtCore.QRect(1050, 200, 61, 41))
        self.seg1_172.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_172.setAutoFillBackground(True)
        self.seg1_172.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_172.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_172.setDigitCount(2)
        self.seg1_172.setObjectName("seg1_172")
        self.seg1_252 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_252.setGeometry(QtCore.QRect(1050, 320, 61, 41))
        self.seg1_252.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_252.setAutoFillBackground(True)
        self.seg1_252.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_252.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_252.setDigitCount(2)
        self.seg1_252.setObjectName("seg1_252")
        self.seg1_225 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_225.setGeometry(QtCore.QRect(560, 360, 61, 41))
        self.seg1_225.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_225.setAutoFillBackground(True)
        self.seg1_225.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_225.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_225.setDigitCount(2)
        self.seg1_225.setObjectName("seg1_225")
        self.seg1_246 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_246.setGeometry(QtCore.QRect(380, 360, 61, 41))
        self.seg1_246.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_246.setAutoFillBackground(True)
        self.seg1_246.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_246.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_246.setDigitCount(2)
        self.seg1_246.setObjectName("seg1_246")
        self.averageTemp1_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp1_LCD.setGeometry(QtCore.QRect(180, 610, 71, 51))
        self.averageTemp1_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp1_LCD.setAutoFillBackground(True)
        self.averageTemp1_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp1_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp1_LCD.setDigitCount(2)
        self.averageTemp1_LCD.setObjectName("averageTemp1_LCD")
        self.seg1_160 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_160.setGeometry(QtCore.QRect(10, 40, 61, 41))
        self.seg1_160.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_160.setAutoFillBackground(True)
        self.seg1_160.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_160.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_160.setDigitCount(2)
        self.seg1_160.setObjectName("seg1_160")
        self.seg1_278 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_278.setGeometry(QtCore.QRect(190, 360, 61, 41))
        self.seg1_278.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_278.setAutoFillBackground(True)
        self.seg1_278.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_278.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_278.setDigitCount(2)
        self.seg1_278.setObjectName("seg1_278")
        self.seg1_277 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_277.setGeometry(QtCore.QRect(990, 360, 61, 41))
        self.seg1_277.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_277.setAutoFillBackground(True)
        self.seg1_277.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_277.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_277.setDigitCount(2)
        self.seg1_277.setObjectName("seg1_277")
        self.seg1_133 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_133.setGeometry(QtCore.QRect(620, 40, 61, 41))
        self.seg1_133.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_133.setAutoFillBackground(True)
        self.seg1_133.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_133.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_133.setDigitCount(2)
        self.seg1_133.setObjectName("seg1_133")
        self.seg1_218 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_218.setGeometry(QtCore.QRect(810, 440, 61, 41))
        self.seg1_218.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_218.setAutoFillBackground(True)
        self.seg1_218.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_218.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_218.setDigitCount(2)
        self.seg1_218.setObjectName("seg1_218")
        self.seg1_237 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_237.setGeometry(QtCore.QRect(930, 400, 61, 41))
        self.seg1_237.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_237.setAutoFillBackground(True)
        self.seg1_237.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_237.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_237.setDigitCount(2)
        self.seg1_237.setObjectName("seg1_237")
        self.seg1_241 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_241.setGeometry(QtCore.QRect(380, 320, 61, 41))
        self.seg1_241.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_241.setAutoFillBackground(True)
        self.seg1_241.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_241.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_241.setDigitCount(2)
        self.seg1_241.setObjectName("seg1_241")
        self.seg1_275 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_275.setGeometry(QtCore.QRect(70, 320, 61, 41))
        self.seg1_275.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_275.setAutoFillBackground(True)
        self.seg1_275.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_275.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_275.setDigitCount(2)
        self.seg1_275.setObjectName("seg1_275")
        self.seg1_120 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_120.setGeometry(QtCore.QRect(10, 360, 61, 41))
        self.seg1_120.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_120.setAutoFillBackground(True)
        self.seg1_120.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_120.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_120.setDigitCount(2)
        self.seg1_120.setObjectName("seg1_120")
        self.seg1_145 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_145.setGeometry(QtCore.QRect(190, 120, 61, 41))
        self.seg1_145.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_145.setAutoFillBackground(True)
        self.seg1_145.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_145.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_145.setDigitCount(2)
        self.seg1_145.setObjectName("seg1_145")
        self.seg1_134 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_134.setGeometry(QtCore.QRect(990, 40, 61, 41))
        self.seg1_134.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_134.setAutoFillBackground(True)
        self.seg1_134.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_134.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_134.setDigitCount(2)
        self.seg1_134.setObjectName("seg1_134")
        self.seg1_146 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_146.setGeometry(QtCore.QRect(10, 160, 61, 41))
        self.seg1_146.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_146.setAutoFillBackground(True)
        self.seg1_146.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_146.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_146.setDigitCount(2)
        self.seg1_146.setObjectName("seg1_146")
        self.seg1_201 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_201.setGeometry(QtCore.QRect(930, 120, 61, 41))
        self.seg1_201.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_201.setAutoFillBackground(True)
        self.seg1_201.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_201.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_201.setDigitCount(2)
        self.seg1_201.setObjectName("seg1_201")
        self.averageTemp5_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp5_LCD.setGeometry(QtCore.QRect(500, 610, 71, 51))
        self.averageTemp5_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp5_LCD.setAutoFillBackground(True)
        self.averageTemp5_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp5_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp5_LCD.setDigitCount(2)
        self.averageTemp5_LCD.setObjectName("averageTemp5_LCD")
        self.averageTemp0_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp0_LCD.setGeometry(QtCore.QRect(100, 610, 71, 51))
        self.averageTemp0_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp0_LCD.setAutoFillBackground(True)
        self.averageTemp0_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp0_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp0_LCD.setDigitCount(2)
        self.averageTemp0_LCD.setObjectName("averageTemp0_LCD")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(420, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(True)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.seg1_220 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_220.setGeometry(QtCore.QRect(930, 360, 61, 41))
        self.seg1_220.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_220.setAutoFillBackground(True)
        self.seg1_220.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_220.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_220.setDigitCount(2)
        self.seg1_220.setObjectName("seg1_220")
        self.seg1_178 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_178.setGeometry(QtCore.QRect(250, 80, 61, 41))
        self.seg1_178.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_178.setAutoFillBackground(True)
        self.seg1_178.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_178.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_178.setDigitCount(2)
        self.seg1_178.setObjectName("seg1_178")
        self.seg1_140 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_140.setGeometry(QtCore.QRect(380, 120, 61, 41))
        self.seg1_140.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_140.setAutoFillBackground(True)
        self.seg1_140.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_140.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_140.setDigitCount(2)
        self.seg1_140.setObjectName("seg1_140")
        self.seg1_190 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_190.setGeometry(QtCore.QRect(810, 80, 61, 41))
        self.seg1_190.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_190.setAutoFillBackground(True)
        self.seg1_190.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_190.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_190.setDigitCount(2)
        self.seg1_190.setObjectName("seg1_190")
        self.seg1_192 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_192.setGeometry(QtCore.QRect(990, 200, 61, 41))
        self.seg1_192.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_192.setAutoFillBackground(True)
        self.seg1_192.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_192.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_192.setDigitCount(2)
        self.seg1_192.setObjectName("seg1_192")
        self.seg1_122 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_122.setGeometry(QtCore.QRect(130, 440, 61, 41))
        self.seg1_122.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_122.setAutoFillBackground(True)
        self.seg1_122.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_122.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_122.setDigitCount(2)
        self.seg1_122.setObjectName("seg1_122")
        self.seg1_198 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_198.setGeometry(QtCore.QRect(990, 120, 61, 41))
        self.seg1_198.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_198.setAutoFillBackground(True)
        self.seg1_198.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_198.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_198.setDigitCount(2)
        self.seg1_198.setObjectName("seg1_198")
        self.seg1_247 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_247.setGeometry(QtCore.QRect(930, 480, 61, 41))
        self.seg1_247.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_247.setAutoFillBackground(True)
        self.seg1_247.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_247.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_247.setDigitCount(2)
        self.seg1_247.setObjectName("seg1_247")
        self.seg1_177 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_177.setGeometry(QtCore.QRect(930, 80, 61, 41))
        self.seg1_177.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_177.setAutoFillBackground(True)
        self.seg1_177.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_177.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_177.setDigitCount(2)
        self.seg1_177.setObjectName("seg1_177")
        self.seg1_189 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_189.setGeometry(QtCore.QRect(500, 80, 61, 41))
        self.seg1_189.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_189.setAutoFillBackground(True)
        self.seg1_189.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_189.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_189.setDigitCount(2)
        self.seg1_189.setObjectName("seg1_189")
        self.seg1_137 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_137.setGeometry(QtCore.QRect(440, 200, 61, 41))
        self.seg1_137.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_137.setAutoFillBackground(True)
        self.seg1_137.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_137.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_137.setDigitCount(2)
        self.seg1_137.setObjectName("seg1_137")
        self.seg1_191 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_191.setGeometry(QtCore.QRect(990, 80, 61, 41))
        self.seg1_191.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_191.setAutoFillBackground(True)
        self.seg1_191.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_191.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_191.setDigitCount(2)
        self.seg1_191.setObjectName("seg1_191")
        self.seg1_249 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_249.setGeometry(QtCore.QRect(990, 320, 61, 41))
        self.seg1_249.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_249.setAutoFillBackground(True)
        self.seg1_249.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_249.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_249.setDigitCount(2)
        self.seg1_249.setObjectName("seg1_249")
        self.seg1_197 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_197.setGeometry(QtCore.QRect(810, 240, 61, 41))
        self.seg1_197.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_197.setAutoFillBackground(True)
        self.seg1_197.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_197.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_197.setDigitCount(2)
        self.seg1_197.setObjectName("seg1_197")
        self.seg1_102 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_102.setGeometry(QtCore.QRect(870, 120, 61, 41))
        self.seg1_102.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_102.setAutoFillBackground(True)
        self.seg1_102.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_102.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_102.setDigitCount(2)
        self.seg1_102.setObjectName("seg1_102")
        self.seg1_269 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_269.setGeometry(QtCore.QRect(130, 320, 61, 41))
        self.seg1_269.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_269.setAutoFillBackground(True)
        self.seg1_269.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_269.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_269.setDigitCount(2)
        self.seg1_269.setObjectName("seg1_269")
        self.seg1_173 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_173.setGeometry(QtCore.QRect(1050, 40, 61, 41))
        self.seg1_173.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_173.setAutoFillBackground(True)
        self.seg1_173.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_173.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_173.setDigitCount(2)
        self.seg1_173.setObjectName("seg1_173")
        self.seg1_162 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_162.setGeometry(QtCore.QRect(380, 40, 61, 41))
        self.seg1_162.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_162.setAutoFillBackground(True)
        self.seg1_162.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_162.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_162.setDigitCount(2)
        self.seg1_162.setObjectName("seg1_162")
        self.seg1_207 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_207.setGeometry(QtCore.QRect(750, 440, 61, 41))
        self.seg1_207.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_207.setAutoFillBackground(True)
        self.seg1_207.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_207.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_207.setDigitCount(2)
        self.seg1_207.setObjectName("seg1_207")
        self.seg1_243 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_243.setGeometry(QtCore.QRect(380, 440, 61, 41))
        self.seg1_243.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_243.setAutoFillBackground(True)
        self.seg1_243.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_243.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_243.setDigitCount(2)
        self.seg1_243.setObjectName("seg1_243")
        self.seg1_139 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_139.setGeometry(QtCore.QRect(310, 80, 61, 41))
        self.seg1_139.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_139.setAutoFillBackground(True)
        self.seg1_139.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_139.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_139.setDigitCount(2)
        self.seg1_139.setObjectName("seg1_139")
        self.seg1_184 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_184.setGeometry(QtCore.QRect(680, 120, 61, 41))
        self.seg1_184.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_184.setAutoFillBackground(True)
        self.seg1_184.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_184.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_184.setDigitCount(2)
        self.seg1_184.setObjectName("seg1_184")
        self.seg1_200 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_200.setGeometry(QtCore.QRect(1050, 160, 61, 41))
        self.seg1_200.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_200.setAutoFillBackground(True)
        self.seg1_200.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_200.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_200.setDigitCount(2)
        self.seg1_200.setObjectName("seg1_200")
        self.seg1_161 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_161.setGeometry(QtCore.QRect(440, 240, 61, 41))
        self.seg1_161.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_161.setAutoFillBackground(True)
        self.seg1_161.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_161.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_161.setDigitCount(2)
        self.seg1_161.setObjectName("seg1_161")
        self.seg1_262 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_262.setGeometry(QtCore.QRect(990, 440, 61, 41))
        self.seg1_262.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_262.setAutoFillBackground(True)
        self.seg1_262.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_262.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_262.setDigitCount(2)
        self.seg1_262.setObjectName("seg1_262")
        self.seg1_208 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_208.setGeometry(QtCore.QRect(870, 360, 61, 41))
        self.seg1_208.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_208.setAutoFillBackground(True)
        self.seg1_208.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_208.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_208.setDigitCount(2)
        self.seg1_208.setObjectName("seg1_208")
        self.seg1_234 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_234.setGeometry(QtCore.QRect(680, 320, 61, 41))
        self.seg1_234.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_234.setAutoFillBackground(True)
        self.seg1_234.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_234.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_234.setDigitCount(2)
        self.seg1_234.setObjectName("seg1_234")
        self.averageTemp3_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averageTemp3_LCD.setGeometry(QtCore.QRect(340, 610, 71, 51))
        self.averageTemp3_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.averageTemp3_LCD.setAutoFillBackground(True)
        self.averageTemp3_LCD.setFrameShape(QtWidgets.QFrame.Panel)
        self.averageTemp3_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.averageTemp3_LCD.setDigitCount(2)
        self.averageTemp3_LCD.setObjectName("averageTemp3_LCD")
        self.seg1_98 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_98.setGeometry(QtCore.QRect(130, 120, 61, 41))
        self.seg1_98.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_98.setAutoFillBackground(True)
        self.seg1_98.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_98.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_98.setDigitCount(2)
        self.seg1_98.setObjectName("seg1_98")
        self.seg1_258 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_258.setGeometry(QtCore.QRect(620, 360, 61, 41))
        self.seg1_258.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_258.setAutoFillBackground(True)
        self.seg1_258.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_258.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_258.setDigitCount(2)
        self.seg1_258.setObjectName("seg1_258")
        self.seg1_245 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_245.setGeometry(QtCore.QRect(870, 400, 61, 41))
        self.seg1_245.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_245.setAutoFillBackground(True)
        self.seg1_245.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_245.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_245.setDigitCount(2)
        self.seg1_245.setObjectName("seg1_245")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.seg1_159 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_159.setGeometry(QtCore.QRect(70, 240, 61, 41))
        self.seg1_159.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_159.setAutoFillBackground(True)
        self.seg1_159.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_159.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_159.setDigitCount(2)
        self.seg1_159.setObjectName("seg1_159")
        self.seg1_185 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_185.setGeometry(QtCore.QRect(250, 200, 61, 41))
        self.seg1_185.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_185.setAutoFillBackground(True)
        self.seg1_185.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_185.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_185.setDigitCount(2)
        self.seg1_185.setObjectName("seg1_185")
        self.seg1_195 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_195.setGeometry(QtCore.QRect(930, 200, 61, 41))
        self.seg1_195.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_195.setAutoFillBackground(True)
        self.seg1_195.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_195.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_195.setDigitCount(2)
        self.seg1_195.setObjectName("seg1_195")
        self.seg1_285 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_285.setGeometry(QtCore.QRect(620, 480, 61, 41))
        self.seg1_285.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_285.setAutoFillBackground(True)
        self.seg1_285.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_285.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_285.setDigitCount(2)
        self.seg1_285.setObjectName("seg1_285")
        self.seg1_100 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_100.setGeometry(QtCore.QRect(130, 200, 61, 41))
        self.seg1_100.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_100.setAutoFillBackground(True)
        self.seg1_100.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_100.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_100.setDigitCount(2)
        self.seg1_100.setObjectName("seg1_100")
        self.seg1_99 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_99.setGeometry(QtCore.QRect(500, 120, 61, 41))
        self.seg1_99.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_99.setAutoFillBackground(True)
        self.seg1_99.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_99.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_99.setDigitCount(2)
        self.seg1_99.setObjectName("seg1_99")
        self.seg1_152 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_152.setGeometry(QtCore.QRect(500, 40, 61, 41))
        self.seg1_152.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_152.setAutoFillBackground(True)
        self.seg1_152.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_152.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_152.setDigitCount(2)
        self.seg1_152.setObjectName("seg1_152")
        self.seg1_119 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_119.setGeometry(QtCore.QRect(750, 360, 61, 41))
        self.seg1_119.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_119.setAutoFillBackground(True)
        self.seg1_119.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_119.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_119.setDigitCount(2)
        self.seg1_119.setObjectName("seg1_119")
        self.seg1_272 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_272.setGeometry(QtCore.QRect(250, 320, 61, 41))
        self.seg1_272.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_272.setAutoFillBackground(True)
        self.seg1_272.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_272.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_272.setDigitCount(2)
        self.seg1_272.setObjectName("seg1_272")
        self.seg1_239 = QtWidgets.QLCDNumber(self.centralwidget)
        self.seg1_239.setGeometry(QtCore.QRect(810, 520, 61, 41))
        self.seg1_239.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seg1_239.setAutoFillBackground(True)
        self.seg1_239.setFrameShape(QtWidgets.QFrame.Panel)
        self.seg1_239.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seg1_239.setDigitCount(2)
        self.seg1_239.setObjectName("seg1_239")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(750, 290, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(True)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Module 3"))
        self.label_14.setText(_translate("MainWindow", "Module 1"))
        self.label_9.setText(_translate("MainWindow", "Module 1"))
        self.label_11.setText(_translate("MainWindow", "Module 3"))
        self.label_7.setText(_translate("MainWindow", "Average"))
        self.label_17.setText(_translate("MainWindow", "Module 4"))
        self.label_10.setText(_translate("MainWindow", "Module 2"))
        self.label_15.setText(_translate("MainWindow", "Module 2"))
        self.label_8.setText(_translate("MainWindow", "Module 0"))
        self.label_13.setText(_translate("MainWindow", "Module 5"))
        self.label_12.setText(_translate("MainWindow", "Module 4"))
        self.label_6.setText(_translate("MainWindow", "Module 0"))
        self.label_18.setText(_translate("MainWindow", "Module 5"))
